### ISSUE TITLE
hand-drawn schematic - an alternative

### ISSUE THREAD

**Issue by cw789** [Jerey/weatherstation-client#1]
Not an issue - but I think my solution could be an alternative to the hand-drawn schematic.
I would try to use [draw.io](https://www.draw.io/) with its included electrical schemes.
It's open-source & free and additionally usable in an offline version.

I hadn't this by hand back at the super bowl.

I use it nowadays for the diagrams within my software documentations (using the [C4 Model](https://c4model.com/)).
I export the diagrams as a SVG with the option "Include a copy of my diagram".
It then will include the diagram.io format into the SVG, which will enable you to edit the SVG later with draw.io by opening the SVG. So I only need to keep the SVG.

**Comment by Jerey** [comment]
Thanks for the note. I have now redrawn the schematic with draw.io.
